// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaRuQHf---g6MBUpWxNM82r5m0iVMVL24',
    appId: '1:406641104689:web:7ce54a7fd7d0276bfd0210',
    messagingSenderId: '406641104689',
    projectId: 'aqua-gallery',
    authDomain: 'aqua-gallery.firebaseapp.com',
    storageBucket: 'aqua-gallery.firebasestorage.app',
    measurementId: 'G-DDS1ZB0GJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCACfboUIFcHFWp4LjgSGLv6eMnhpihy44',
    appId: '1:406641104689:android:13f3e4021cc4572afd0210',
    messagingSenderId: '406641104689',
    projectId: 'aqua-gallery',
    storageBucket: 'aqua-gallery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqddjP0z2gTT7TT6s5VPXvYX5Awf8HsoM',
    appId: '1:406641104689:ios:c49da4043393247afd0210',
    messagingSenderId: '406641104689',
    projectId: 'aqua-gallery',
    storageBucket: 'aqua-gallery.firebasestorage.app',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqddjP0z2gTT7TT6s5VPXvYX5Awf8HsoM',
    appId: '1:406641104689:ios:c49da4043393247afd0210',
    messagingSenderId: '406641104689',
    projectId: 'aqua-gallery',
    storageBucket: 'aqua-gallery.firebasestorage.app',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaRuQHf---g6MBUpWxNM82r5m0iVMVL24',
    appId: '1:406641104689:web:397b021570144365fd0210',
    messagingSenderId: '406641104689',
    projectId: 'aqua-gallery',
    authDomain: 'aqua-gallery.firebaseapp.com',
    storageBucket: 'aqua-gallery.firebasestorage.app',
    measurementId: 'G-DMJRLNNLG6',
  );
}
